export { HeaderBar }    from "./HeaderBar";
export { TimePanel }    from "./TimePanel";
export { PrayerPanel }  from "./PrayerPanel";
export { ReadingPanel } from "./ReadingPanel";
export { NewsPanel }    from "./NewsPanel";
export { QuranPanel }   from "./QuranPanel";
export { CalendarPanel }from "./CalendarPanel";
export { GymPanel }     from "./GymPanel";
export { FinancePanel } from "./FinancePanel";
export { FilmsPanel }  from "./FilmsPanel";
